//! Subcommand for injecting `Co-authored-by` lines into Git commit messages.

use std::fs;
use std::path::Path;

use crate::active_copirate::ActiveCoPirates;
use crate::BoxResult;

/// Injects `Co-authored-by` lines into the given Git commit message file.
///
/// This subcommand should only ever be invoked by the Git hook generated by `rmob embark`.
pub fn inject_into_commit_message_file(
    commit_message_file: &Path,
    repo_dir: &Path,
) -> BoxResult<()> {
    const PATTERN: &str = "\n# ";

    let commit_message = fs::read_to_string(commit_message_file)?;
    let mob = ActiveCoPirates::get(repo_dir)?;

    let comment_pos = commit_message
        .find(PATTERN)
        .unwrap_or_else(|| commit_message.len().saturating_sub(1));

    let (git_message, git_comments) = commit_message.split_at(comment_pos);
    let updated_message = format!("{}\n\n{}{}", git_message, mob, git_comments);

    fs::write(commit_message_file, updated_message)?;

    Ok(())
}
